<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <ValheimPath Condition="'$(ValheimPath)' == ''">$(VALHEIM_GAME_PATH)</ValheimPath>
    <ManagedPath Condition="'$(ManagedPath)' == ''">$(ValheimPath)/valheim_Data/Managed</ManagedPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../NativeChatReader.cs" Link="NativeChatReader.cs" />
    <Reference Include="assembly_valheim" HintPath="$(ManagedPath)/assembly_valheim.dll" />
    <Reference Include="assembly_utils" HintPath="$(ManagedPath)/assembly_utils.dll" />
    <Reference Include="Splatform" HintPath="$(ManagedPath)/Splatform.dll" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(ManagedPath)/UnityEngine.CoreModule.dll" />
  </ItemGroup>
</Project>
